### ISSUE TITLE
Does not work any more (5th January 2024)

### ISSUE THREAD

**Issue by ChrisJan00** [N1ck/gifs-for-github#68]
Hello.  I downloaded this extension from the Firefox addons page months ago, and have been happily using it all along. 

Today it stopped working.  I was using it a couple of days ago, it only started failing now.

The Javascript console shows a bunch of errors "Content-Security-Policy: The page’s settings blocked the loading of a resource at ...".  

I have not updated Firefox in weeks, and this just started happening now, so probably the Github people just changed something that broke the extension.  Hopefully you can figure a workaround to make it work again.  This awesome addon is missed.

Not sure if it matters:
Firefox version 119.0 (64-bit)
Gifs For Github version 23.11.6

**Comment by N1ck** [comment]
<img src="https://media4.giphy.com/media/3rgXByB0tbT7oXK7Xq/giphy.gif"/>

Thank you for reporting that the extension stopped working. You're right, GitHub has made some changes that caused the extension to break.

The fix for the recent changes are here: https://github.com/N1ck/gifs-for-github/pull/69/files (plus this sneaky additional fix [here](https://github.com/N1ck/gifs-for-github/commit/b327b0b914703b4fc8bf3b70d51d6f6b6373bf4e)) 

It is already available in version `24.1.6`, currently just in FIrefox and is awaiting review to be updated in Chrome but should be soon 🤞 

Thank you very much @mxosman also for investigating.

<img src="https://media0.giphy.com/media/mbhseRYedlG5W/giphy.gif"/>

**Comment by ChrisJan00** [comment]
Thank you! It's working again! :heart: 
<img src="https://media4.giphy.com/media/3rgXBQIDHkFNniTNRu/giphy.gif"/>

**Comment by mxosman** [comment]
<img src="https://media0.giphy.com/media/xULW8niR8Igcuafth6/giphy.gif"/>
